### ISSUE TITLE
Nice theme but...

### ISSUE THREAD

**Issue by lassejlv** [sinamombeiny/S-DarkTheme.zed#1]
I love this theme, but would like to know if you could fix colors make them darker or just better when hover. You cannot really see them. Example on images

ERROR:
<img width="518" alt="Screenshot 2024-11-21 at 20 53 23" src="https://github.com/user-attachments/assets/6eff7564-1c1f-499c-806a-c686f998624a">

WARNING:
<img width="727" alt="Screenshot 2024-11-21 at 20 54 54" src="https://github.com/user-attachments/assets/6adf775c-f3b8-48bb-a279-42cdc54db4a3">

**Comment by SinaMombeiny** [comment]
Hey, please update the theme extension.
